[theme]
primaryColor = "#00B1A9"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A202C"
font = "sans serif"

[client]
toolbarMode = "viewer"
showSidebarNavigation = false
